version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cinematch-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=cinematch_super_secret_devops_key_2026
      - S3_BUCKET_NAME=cinematch-movie-posters-bucket
    networks:
      - cinematch-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinematch-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cinematch-network

networks:
  cinematch-network:
    driver: bridge
